version: "3.4"

x-common-mysql-env: &common-mysql-env
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: admin
  MYSQL_PASSWORD: 0000

services:
  mysql:
    platform: linux/amd64
    container_name: mysql-local
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test_db
      <<: *common-mysql-env
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
